workflows:
  my-ios-build:
    name: iOS Build and App Store Deployment
    max_build_duration: 60
    
    environment:
      groups:
        - app_store_credentials
      vars:
        BUNDLE_ID: "com.footmastrs.socc"
        XCODE_PROJECT: "FootbollQuize.xcodeproj"
        XCODE_SCHEME: "FootbollQuize"
      xcode: latest
    
    scripts:
      - name: Set up keychain
        script: keychain initialize
          
      - name: Force Generate Signing Files (Via Fastfile)
        script: |
          # 1. Создаем папку для Fastlane, если её нет
          mkdir -p fastlane

          # 2. Создаем Fastfile прямо на лету
          # Это решает проблему с видимостью классов и передачей параметров
          cat <<EOF > fastlane/Fastfile
          default_platform(:ios)
          platform :ios do
            lane :setup_signing do
              # Настраиваем API Key
              api_key = app_store_connect_api_key(
                key_id: ENV['APP_STORE_CONNECT_KEY_IDENTIFIER'],
                issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
                key_content: ENV['APP_STORE_CONNECT_PRIVATE_KEY'],
                duration: 1200,
                in_house: false
              )

              # Генерируем Сертификат (force: true создает НОВЫЙ с ключом локально)
              get_certificates(
                api_key: api_key,
                type: "distribution",
                readonly: false,
                force: true 
              )

              # Генерируем Профиль
              get_provisioning_profile(
                api_key: api_key,
                app_identifier: ENV['BUNDLE_ID'],
                type: "appstore",
                readonly: false,
                force: true
              )
            end
          end
          EOF
          
          # 3. Запускаем этот лейн
          fastlane setup_signing

      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
          
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
            
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
