workflows:
  my-ios-build:
    name: iOS Build and App Store Deployment
    max_build_duration: 60
    
    environment:
      groups:
        - app_store_credentials
      vars:
        BUNDLE_ID: "com.footmastrs.socc"
        
        XCODE_PROJECT: "FootbollQuize.xcodeproj"
        XCODE_SCHEME: "FootbollQuize"
      
      xcode: latest
    
    scripts:
      
      # Инициализация связки ключей остается
      - name: Set up keychain
        script: |
          keychain initialize
          
      # 1. ЕДИНЫЙ ШАГ: Создание/Установка Сертификата И Получение Профилей
      - name: Fetch and Install Signing Files
        script: |
          # Эта команда использует P8-ключ:
          # 1. Проверяет наличие сертификата IOS_DISTRIBUTION. Если его нет, создает его.
          # 2. Устанавливает этот сертификат (включая приватный ключ) в связку ключей.
          # 3. Получает или создает профиль IOS_APP_STORE, используя этот сертификат.
          # 4. Сохраняет профиль локально.
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --certificate-type IOS_DISTRIBUTION # <-- Это ключевой флаг!
            
      # 2. ПРИМЕНЕНИЕ ПРОФИЛЕЙ К ПРОЕКТУ
      - name: Set up code signing settings on Xcode project
        script: |
          # Применяем скачанные профили к проекту
          xcode-project use-profiles
          
      # 3. СБОРКА IPA
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
            
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
