workflows:
  my-ios-build:
    name: iOS Build and App Store Deployment
    max_build_duration: 60
    
    environment:
      groups:
        - app_store_credentials # Проверь, что тут есть KEY_ID, ISSUER_ID и само тело KEY
      vars:
        BUNDLE_ID: "com.footmastrs.socc"
        XCODE_PROJECT: "FootbollQuize.xcodeproj"
        XCODE_SCHEME: "FootbollQuize"
      xcode: latest
    
    scripts:
      - name: Set up keychain
        script: keychain initialize
          
      - name: Force Generate Signing Files (Ruby script)
        script: |
          # Создаем скрипт на лету, чтобы не мучиться с аргументами шелла
          cat <<EOF > build_certs.rb
          require 'fastlane'
          
          # 1. Настраиваем подключение к API
          api_key = Fastlane::Actions::AppStoreConnectApiKeyAction.run(
            key_id: ENV['APP_STORE_CONNECT_KEY_IDENTIFIER'],
            issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
            key_content: ENV['APP_STORE_CONNECT_PRIVATE_KEY'],
            duration: 1200,
            in_house: false
          )
          
          # 2. Генерируем сертификат (cert)
          # force: true - КЛЮЧЕВОЙ МОМЕНТ. Создаст новый cert + приватный ключ локально, 
          # даже если на портале уже есть другие сертификаты.
          Fastlane::Actions::GetCertificatesAction.run(
            api_key: api_key,
            type: "distribution",
            readonly: false,
            force: true 
          )
          
          # 3. Генерируем профиль (sigh)
          # force: true - пересоздаст профиль, чтобы он привязался к НОВОМУ сертификату
          Fastlane::Actions::GetProvisioningProfileAction.run(
            api_key: api_key,
            app_identifier: ENV['BUNDLE_ID'],
            type: "appstore",
            readonly: false,
            force: true
          )
          EOF
          
          # Запускаем этот скрипт
          ruby build_certs.rb

      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
          
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
            
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
