workflows:
  my-ios-build:
    name: iOS Build and App Store Deployment
    max_build_duration: 60
    
    environment:
      groups:
        - app_store_credentials
      vars:
        BUNDLE_ID: "com.footmastrs.socc"
        XCODE_PROJECT: "FootbollQuize.xcodeproj"
        XCODE_SCHEME: "FootbollQuize"
      xcode: latest
    
    scripts:
      - name: Set up keychain
        script: keychain initialize
          
      - name: Fetch Signing Files via Fastlane
        script: |
          # 1. Сохраняем ключ из переменной во временный файл (Fastlane требует файл)
          echo "$APP_STORE_CONNECT_PRIVATE_KEY" > /tmp/auth_key.p8
          
          # 2. Генерируем или скачиваем Сертификат (и создает приватный ключ локально!)
          fastlane run get_certificates \
             api_key_path:"/tmp/auth_key.p8" \
             key_id:"$APP_STORE_CONNECT_KEY_IDENTIFIER" \
             issuer_id:"$APP_STORE_CONNECT_ISSUER_ID" \
             type:"distribution" \
             readonly:false
             
          # 3. Генерируем или скачиваем Профиль
          fastlane run get_provisioning_profile \
             api_key_path:"/tmp/auth_key.p8" \
             key_id:"$APP_STORE_CONNECT_KEY_IDENTIFIER" \
             issuer_id:"$APP_STORE_CONNECT_ISSUER_ID" \
             app_identifier:"$BUNDLE_ID" \
             type:"appstore" \
             readonly:false

          # Удаляем временный ключ
          rm /tmp/auth_key.p8

      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
          
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
            
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
