workflows:
  my-ios-build:
    name: iOS Build and App Store Deployment
    max_build_duration: 60
    
    environment:
      groups:
        - app_store_credentials # Убедись, что переменные (KEY, ISSUER_ID, KEY_ID) здесь заданы верно
      vars:
        BUNDLE_ID: "com.footmastrs.socc"
        XCODE_PROJECT: "FootbollQuize.xcodeproj"
        XCODE_SCHEME: "FootbollQuize"
      xcode: latest
    
    scripts:
      - name: Set up keychain
        script: keychain initialize
          
      - name: Fetch Signing Files (Codemagic CLI)
        script: |
          # Эта команда сама берет ключи из environment groups
          # Сама генерирует/скачивает сертификат и профиль
          # И кладет их куда нужно для xcode-project
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create

      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
          
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
            
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
